name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test installer generation
        run: |
          # Generate installer
          bash scripts/generate_installer.sh
          
          # Verify installer exists
          test -f dist/install.sh || { echo "Installer not generated"; exit 1; }
          
          # Create test directory
          mkdir -p test-dir
          cd test-dir
          
          # Test installer
          bash ../dist/install.sh
          
          # Verify Makefile was created
          test -f Makefile || { echo "Makefile not created"; exit 1; }
          
          # Verify targets are available
          make -n dump || { echo "dump target not available"; exit 1; }
          make -n version || { echo "version target not available"; exit 1; }
          
          # Test Makefile content
          grep "MKTOOLS_VERSION" Makefile || { echo "Version information missing"; exit 1; }
          grep "dump:" Makefile || { echo "dump target missing"; exit 1; }
          
          echo "All tests passed!"

      - name: Test installer idempotency
        run: |
          cd test-dir
          
          # Capture original Makefile
          cp Makefile Makefile.orig
          
          # Run installer again
          bash ../dist/install.sh
          
          # Compare files
          diff Makefile Makefile.orig || { echo "Installer modified existing Makefile"; exit 1; }
          
          echo "Idempotency test passed!"

      - name: Test with existing Makefile
        run: |
          mkdir -p test-dir-existing
          cd test-dir-existing
          
          # Create a simple Makefile with existing content
          echo -e ".PHONY: test\n\ntest:\n\techo \"test\"" > Makefile
          
          # Run installer
          bash ../dist/install.sh
          
          # Verify original target still exists
          make -n test || { echo "Original target lost"; exit 1; }
          
          # Verify new targets are available
          make -n dump || { echo "dump target not available"; exit 1; }
          make -n version || { echo "version target not available"; exit 1; }
          
          echo "Existing Makefile test passed!"